ARG IMAGE=
FROM ${IMAGE}
ARG UNAME=builder
ARG UID=1000
ARG GID=1000
RUN rm -rf /home/*
RUN groupadd -g $GID $UNAME || :
RUN useradd -m -u $UID -g $GID -s /bin/bash $UNAME
USER $UNAME
CMD [ "/bin/bash", "--login" ]